include ../CommonDefs.mak

BIN_DIR = Bin

SRC_FILES = \
	src/com/primesense/nite/Samples/UserViewer/*.java

JAR_NAME = com.primesense.nite.Samples.UserViewer
USED_JARS = org.openni com.primesense.nite
MAIN_CLASS = com.primesense.nite.Samples.UserViewer.UserViewerApplication

include ../CommonJavaMakefile
