// Generated by gencpp from file frontier_exploration/BlacklistPoint.msg
// DO NOT EDIT!


#ifndef FRONTIER_EXPLORATION_MESSAGE_BLACKLISTPOINT_H
#define FRONTIER_EXPLORATION_MESSAGE_BLACKLISTPOINT_H

#include <ros/service_traits.h>


#include <frontier_exploration/BlacklistPointRequest.h>
#include <frontier_exploration/BlacklistPointResponse.h>


namespace frontier_exploration
{

struct BlacklistPoint
{

typedef BlacklistPointRequest Request;
typedef BlacklistPointResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct BlacklistPoint
} // namespace frontier_exploration


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::frontier_exploration::BlacklistPoint > {
  static const char* value()
  {
    return "a7c84ff13976aa04656e56e300124444";
  }

  static const char* value(const ::frontier_exploration::BlacklistPoint&) { return value(); }
};

template<>
struct DataType< ::frontier_exploration::BlacklistPoint > {
  static const char* value()
  {
    return "frontier_exploration/BlacklistPoint";
  }

  static const char* value(const ::frontier_exploration::BlacklistPoint&) { return value(); }
};


// service_traits::MD5Sum< ::frontier_exploration::BlacklistPointRequest> should match 
// service_traits::MD5Sum< ::frontier_exploration::BlacklistPoint > 
template<>
struct MD5Sum< ::frontier_exploration::BlacklistPointRequest>
{
  static const char* value()
  {
    return MD5Sum< ::frontier_exploration::BlacklistPoint >::value();
  }
  static const char* value(const ::frontier_exploration::BlacklistPointRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::frontier_exploration::BlacklistPointRequest> should match 
// service_traits::DataType< ::frontier_exploration::BlacklistPoint > 
template<>
struct DataType< ::frontier_exploration::BlacklistPointRequest>
{
  static const char* value()
  {
    return DataType< ::frontier_exploration::BlacklistPoint >::value();
  }
  static const char* value(const ::frontier_exploration::BlacklistPointRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::frontier_exploration::BlacklistPointResponse> should match 
// service_traits::MD5Sum< ::frontier_exploration::BlacklistPoint > 
template<>
struct MD5Sum< ::frontier_exploration::BlacklistPointResponse>
{
  static const char* value()
  {
    return MD5Sum< ::frontier_exploration::BlacklistPoint >::value();
  }
  static const char* value(const ::frontier_exploration::BlacklistPointResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::frontier_exploration::BlacklistPointResponse> should match 
// service_traits::DataType< ::frontier_exploration::BlacklistPoint > 
template<>
struct DataType< ::frontier_exploration::BlacklistPointResponse>
{
  static const char* value()
  {
    return DataType< ::frontier_exploration::BlacklistPoint >::value();
  }
  static const char* value(const ::frontier_exploration::BlacklistPointResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FRONTIER_EXPLORATION_MESSAGE_BLACKLISTPOINT_H
